"""Tektronix DPO4000 utility package."""

from .advanced_trigger import CapabilityProbeResult, DEFAULT_CAPABILITY_PROBE_TIMEOUT_MS
from .bus import BusConfig
from .connection import (
    build_tcpip_instr_resource,
    build_tcpip_socket_resource,
    list_visa_resources,
    visaResourceAddr,
)
from .control import (
    AcquisitionConfig,
    ChannelConfig,
    DisplayConfig,
    MathConfig,
    MeasurementConfig,
    MeasurementSetup,
    SequenceTriggerConfig,
    TriggerConfig,
)
from .errors import (
    DPOCleanupError,
    DPOConnectionError,
    DPOError,
    DPOImageCaptureError,
    DPONotConnectedError,
    DPOProtocolError,
    DPOSettingsError,
    DPOTimeoutError,
    DPOTransportError,
    DPOWaveformError,
)
from .hardcopy import extract_png_bytes, strip_ieee_block_header
from .reference import ReferenceConfig
from .instrument import DPO4000Scope, DPO4054
from .rules import (
    CompareOperator,
    LogicOperator,
    RuleEngine,
    RuleEvaluation,
    RuleGroup,
    RuleSet,
    RuleSetResult,
    RuleStatus,
    RuleValidationError,
    ScalarRule,
    recipe_result_values,
    rule_set_from_mapping,
    rule_set_to_mapping,
)
from .session import scope_session
from .waveform import (
    WaveformData,
    WaveformPreamble,
    WaveformRequest,
    parse_ascii_curve,
    read_channel_waveform_data,
    read_waveform,
)

__all__ = [
    "AcquisitionConfig",
    "BusConfig",
    "CapabilityProbeResult",
    "ChannelConfig",
    "CompareOperator",
    "DEFAULT_CAPABILITY_PROBE_TIMEOUT_MS",
    "DPO4000Scope",
    "DPO4054",
    "DPOCleanupError",
    "DPOConnectionError",
    "DPOError",
    "DPOImageCaptureError",
    "DPONotConnectedError",
    "DPOProtocolError",
    "DPOSettingsError",
    "DPOTimeoutError",
    "DPOTransportError",
    "DPOWaveformError",
    "DisplayConfig",
    "LogicOperator",
    "MathConfig",
    "MeasurementConfig",
    "MeasurementSetup",
    "ReferenceConfig",
    "RuleEngine",
    "RuleEvaluation",
    "RuleGroup",
    "RuleSet",
    "RuleSetResult",
    "RuleStatus",
    "RuleValidationError",
    "ScalarRule",
    "SequenceTriggerConfig",
    "TriggerConfig",
    "WaveformData",
    "WaveformPreamble",
    "WaveformRequest",
    "visaResourceAddr",
    "build_tcpip_instr_resource",
    "build_tcpip_socket_resource",
    "list_visa_resources",
    "scope_session",
    "extract_png_bytes",
    "strip_ieee_block_header",
    "parse_ascii_curve",
    "read_channel_waveform_data",
    "read_waveform",
    "recipe_result_values",
    "rule_set_from_mapping",
    "rule_set_to_mapping",
]
